# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1coTYrFYdybb6UAameQ4ZJSr3HLbj3_iX
"""

import joblib
import pandas as pd

def run_inference_on_etihad_live(live_df, model_dir='dashboard/models'):
    features_fuel = ['Aircraft_Code', 'Engine_Code', 'Seat_Count', 'Estimated_Passengers',
                     'Weather_Penalty_Index', 'Altitude_Drift', 'Unplanned_Reroute', 'Holding_Loop_Detected']
    features_co2 = features_fuel.copy()
    features_anomaly = ['Aircraft_Code', 'Engine_Code', 'Seat_Count', 'Estimated_Passengers',
                        'Weather_Penalty_Index', 'Altitude_Drift', 'Adjusted_Fuel_Burn_kg',
                        'Adjusted_CO2_kg', 'RTK', 'CO2_per_RTK', 'Predicted_CO2_per_RTK']
    features_revenue = ['Aircraft_Code', 'Engine_Code', 'Seat_Count', 'Estimated_Passengers', 'Yield_USD_per_RPK']
    model_fuel = joblib.load(f'{model_dir}/model_fuel.pkl')
    model_co2 = joblib.load(f'{model_dir}/model_co2.pkl')
    model_anomaly = joblib.load(f'{model_dir}/model_anomaly.pkl')
    model_revenue = joblib.load(f'{model_dir}/model_revenue.pkl')
    live_df['predicted_fuel'] = model_fuel.predict(live_df[features_fuel])
    live_df['predicted_co2'] = model_co2.predict(live_df[features_co2])
    live_df['anomaly_flag_pred'] = model_anomaly.predict(live_df[features_anomaly])
    live_df['predicted_revenue'] = model_revenue.predict(live_df[features_revenue])
    live_df['anomaly_flag_pred'] = live_df['anomaly_flag_pred'].map({0: 'Normal', 1: 'Anomaly'})
    return live_df